[buildPlans.iosevka-st]
family = "Iosevka ST"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-st.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "short-serifed"
capital-w = "curly-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
i = "serifed-asymmetric"
k = "straight-serifless"
l = "serifed-flat-tailed"
t = "flat-hook-short-neck"
w = "curly-serifless"
y = "straight-turn-serifless"
lower-lambda = "straight-turn"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-ef = "serifless"
zero = "oval-unslashed"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
eight = "two-circles"
nine = "open-contour"
asterisk = "penta-mid"
caret = "high"
brace = "straight"
number-sign = "slanted"
at = "fourfold"
dollar = "interrupted"
percent = "rings-continuous-slash"

[buildPlans.iosevka-st.variants.italic]
f = "flat-hook-tailed-crossbar-at-x-height"

[buildPlans.iosevka-st.ligations]
enables  = [
  "center-ops",
  "center-op-trigger-plus-minus-l",
  "center-op-trigger-plus-minus-r",
  "center-op-trigger-equal-l",
  "center-op-trigger-equal-r",
  "center-op-trigger-angle-inside",
  "center-op-trigger-angle-outside",
  "center-op-influence-colon",
  "kern-dotty",
  "kern-bars"
]

[buildPlans.iosevka-st.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-st.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-st.weights.semibold]
shape = 700
menu = 600
css = 600

[buildPlans.iosevka-st.weights.bold]
shape = 800
menu = 700
css = 700

[buildPlans.iosevka-st.weights.extrabold]
shape = 900
menu = 800
css = 800

[buildPlans.iosevka-st.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-st.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

